[tox]
skip_missing_interpreters = true
envlist =
    py{310,311,312,313,314}-django52,
    py{312,313,314}-django60,
    lint,
    prepare_npm,
    release

[testenv]
usedevelop = true
commands = python django_js_reverse/tests/unit_tests.py
deps=
    py{310,311,312}: js2py==0.74
    django52: Django>=5.2,<5.3
    django60: Django>=6.0,<6.1

[testenv:release]
deps =
    build
    django>=5.2,<6.1
allowlist_externals =
    rm
commands =
    rm -rf {toxinidir}/dist
    python -m prepare_npm
    {envpython} -m build --sdist --wheel --outdir={toxinidir}/dist {toxinidir}

[testenv:prepare_npm]
deps =
    django>=5.2,<6.1
commands =
    python -m prepare_npm

[testenv:lint]
commands = {envpython} setup.py check --restructuredtext --strict --metadata
deps =
    docutils<0.22
    setuptools>=69
